name: Migrate Production Database

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

jobs:
  if-merged-migrate-db:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Migrations on Production Database
        run: |
          touch .env

          echo DATABASE_URL=${{ env.DATABASE_URL }} >> .env

          npm run migration:push
